name: 'dbt_segmentation_tools'
version: '1.0.0'

profile: 'dbt_segmentation_tools'


model-paths: ["sample_models"]
macro-paths: ["macros"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
